name: Deploy to Azure Functions for development

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'be/functions' # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '18.x' # set this to the node version to use (e.g. '8.x', '10.x', '12.x')
  project_name: discket
  environment: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - uses: Azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID_DEV }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET_DEV }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "audience": "api://AzureADTokenExchange"
            }
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
          auth-type: SERVICE_PRINCIPAL
      # - uses: Azure/get-keyvault-secrets@v1
      #   with:
      #     keyvault: discketdevkvt
      #     secrets: ''
      #   id: myGetSecretAction

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npx prisma generate
          npm run build --if-present
          npm run test --if-present
          popd
        # env:
        #   DATABASE_URL:

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        env:
          environment: dev
        with:
          app-name: ${{ env.project_name }}-${{ env.environment }}-functions-sb
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV }}
